    
# GENERAL CONFIGURATION #
#version format
version: '1.0.{build}'

#branches to build
branches:
  only:
    - master

#don't build on tags
skip_tags: true

# ENVIRONMENT CONFIGURATION #

clone_folder: c:\%PROJECT_NAME%

shallow_clone: true

clone_depth: 5   

environment:
  PROJECT_NAME: zchxMapTile
  matrix:
  - id: msvc-x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x86
    compiler: msvc-15
    generator: "Visual Studio 15 2017"
    QTDIR: "C:\\Qt\\5.13.0\\msvc2017"
  - id: msvc-x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    compiler: msvc-15
    generator: "Visual Studio 15 2017 Win64"
    QTDIR: "C:\\Qt\\5.13.0\\msvc2017_64"

configuration:
  - Release

install:
  - set PATH=%QTDIR%\bin;%PATH%
  - set ORIGPATH=%PATH%
  
#the build fail once the job fails
matrix:
  fast_finish: true


init:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x86" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x86" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x64" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64



# BUILD CONFIGURATION #
before_build:
    - cd c:\%PROJECT_NAME%
    
    
    
    

build_script:
  - qmake zchxMapTile.pro
  

